# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\40207\OneDrive\OneDriveDocumentation\PythonWorkSpace\serialRT\serialRT\UIArm.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Arm(object):
    def setupUi(self, Arm):
        Arm.setObjectName("Arm")
        Arm.resize(549, 288)
        self.gridLayout_2 = QtWidgets.QGridLayout(Arm)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Pinky = QtWidgets.QGroupBox(Arm)
        self.Pinky.setAlignment(QtCore.Qt.AlignCenter)
        self.Pinky.setObjectName("Pinky")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Pinky)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.bellow2 = Bellow(self.Pinky)
        self.bellow2.setObjectName("bellow2")
        self.gridLayout.addWidget(self.bellow2, 0, 1, 1, 1)
        self.bellow1 = Bellow(self.Pinky)
        self.bellow1.setObjectName("bellow1")
        self.gridLayout.addWidget(self.bellow1, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.bellow3 = Bellow(self.Pinky)
        self.bellow3.setObjectName("bellow3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.bellow3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout.addWidget(self.bellow3, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        self.bellow0 = Bellow(self.Pinky)
        self.bellow0.setObjectName("bellow0")
        self.gridLayout.addWidget(self.bellow0, 1, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 2, 0, 1, 1)
        self.bellow4 = Bellow(self.Pinky)
        self.bellow4.setObjectName("bellow4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.bellow4)
        self.horizontalLayout_9.setSpacing(1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout.addWidget(self.bellow4, 2, 1, 1, 1)
        self.bellow5 = Bellow(self.Pinky)
        self.bellow5.setObjectName("bellow5")
        self.gridLayout.addWidget(self.bellow5, 2, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 2, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.Pinky, 0, 1, 10, 1)
        self.plotDialogButton = QtWidgets.QPushButton(Arm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotDialogButton.sizePolicy().hasHeightForWidth())
        self.plotDialogButton.setSizePolicy(sizePolicy)
        self.plotDialogButton.setObjectName("plotDialogButton")
        self.gridLayout_2.addWidget(self.plotDialogButton, 7, 0, 1, 1)
        self.serialButton = QtWidgets.QPushButton(Arm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serialButton.sizePolicy().hasHeightForWidth())
        self.serialButton.setSizePolicy(sizePolicy)
        self.serialButton.setCheckable(True)
        self.serialButton.setObjectName("serialButton")
        self.gridLayout_2.addWidget(self.serialButton, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 123, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 5, 0, 1, 1)
        self.joyStickButton = QtWidgets.QPushButton(Arm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joyStickButton.sizePolicy().hasHeightForWidth())
        self.joyStickButton.setSizePolicy(sizePolicy)
        self.joyStickButton.setCheckable(True)
        self.joyStickButton.setObjectName("joyStickButton")
        self.gridLayout_2.addWidget(self.joyStickButton, 0, 0, 1, 1)
        self.savePlotButton = QtWidgets.QPushButton(Arm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savePlotButton.sizePolicy().hasHeightForWidth())
        self.savePlotButton.setSizePolicy(sizePolicy)
        self.savePlotButton.setObjectName("savePlotButton")
        self.gridLayout_2.addWidget(self.savePlotButton, 8, 0, 1, 1)
        self.freLabel = QtWidgets.QLabel(Arm)
        self.freLabel.setObjectName("freLabel")
        self.gridLayout_2.addWidget(self.freLabel, 3, 0, 1, 1)
        self.LenLabel = QtWidgets.QLabel(Arm)
        self.LenLabel.setObjectName("LenLabel")
        self.gridLayout_2.addWidget(self.LenLabel, 4, 0, 1, 1)
        self.sinkBellow = Bellow(Arm)
        self.sinkBellow.setObjectName("sinkBellow")
        self.gridLayout_2.addWidget(self.sinkBellow, 6, 0, 1, 1)
        self.forceSensorButton = QtWidgets.QPushButton(Arm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forceSensorButton.sizePolicy().hasHeightForWidth())
        self.forceSensorButton.setSizePolicy(sizePolicy)
        self.forceSensorButton.setCheckable(True)
        self.forceSensorButton.setObjectName("forceSensorButton")
        self.gridLayout_2.addWidget(self.forceSensorButton, 2, 0, 1, 1)

        self.retranslateUi(Arm)
        self.bellow5.sigValueChanged['int','float','int'].connect(Arm.slotValueChanged)
        self.bellow0.sigValueChanged['int','float','int'].connect(Arm.slotValueChanged)
        self.bellow1.sigValueChanged['int','float','int'].connect(Arm.slotValueChanged)
        self.bellow2.sigValueChanged['int','float','int'].connect(Arm.slotValueChanged)
        self.bellow3.sigValueChanged['int','float','int'].connect(Arm.slotValueChanged)
        self.bellow4.sigValueChanged['int','float','int'].connect(Arm.slotValueChanged)
        self.plotDialogButton.clicked.connect(Arm.slotPlotDialogButtonClicked)
        self.savePlotButton.clicked.connect(Arm.slotSavePlotData)
        self.joyStickButton.toggled['bool'].connect(Arm.slotJoyStickClicked)
        self.sinkBellow.sigValueChanged['int','float','int'].connect(Arm.slotValueChanged)
        QtCore.QMetaObject.connectSlotsByName(Arm)

    def retranslateUi(self, Arm):
        _translate = QtCore.QCoreApplication.translate
        Arm.setWindowTitle(_translate("Arm", "Form"))
        self.Pinky.setTitle(_translate("Arm", "Pinky"))
        self.plotDialogButton.setText(_translate("Arm", "Plots"))
        self.serialButton.setText(_translate("Arm", "Sync Soft Hand"))
        self.joyStickButton.setText(_translate("Arm", "JoyStick"))
        self.savePlotButton.setText(_translate("Arm", "SavePlot"))
        self.freLabel.setText(_translate("Arm", "frequency 40 Hz"))
        self.LenLabel.setText(_translate("Arm", "Length 410 mm"))
        self.forceSensorButton.setText(_translate("Arm", "ATI_ForceSensor"))

from bellow import Bellow
