# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\40207\OneDrive\OneDriveDocumentation\PythonWorkSpace\serialRT\serialRT\UIHand.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Hand(object):
    def setupUi(self, Hand):
        Hand.setObjectName("Hand")
        Hand.resize(853, 321)
        self.gridLayout_14 = QtWidgets.QGridLayout(Hand)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem = QtWidgets.QSpacerItem(48, 108, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem, 0, 2, 3, 1)
        self.joyStickButton = QtWidgets.QPushButton(Hand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joyStickButton.sizePolicy().hasHeightForWidth())
        self.joyStickButton.setSizePolicy(sizePolicy)
        self.joyStickButton.setCheckable(True)
        self.joyStickButton.setObjectName("joyStickButton")
        self.gridLayout_13.addWidget(self.joyStickButton, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(78, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem1, 1, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(288, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem2, 8, 2, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(48, 258, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem3, 5, 0, 5, 1)
        self.leapMotionButton = QtWidgets.QPushButton(Hand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leapMotionButton.sizePolicy().hasHeightForWidth())
        self.leapMotionButton.setSizePolicy(sizePolicy)
        self.leapMotionButton.setCheckable(True)
        self.leapMotionButton.setObjectName("leapMotionButton")
        self.gridLayout_13.addWidget(self.leapMotionButton, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(78, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem4, 9, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(358, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem5, 9, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.frametime = QtWidgets.QDoubleSpinBox(Hand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frametime.sizePolicy().hasHeightForWidth())
        self.frametime.setSizePolicy(sizePolicy)
        self.frametime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.frametime.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.frametime.setDecimals(1)
        self.frametime.setSingleStep(0.1)
        self.frametime.setObjectName("frametime")
        self.gridLayout.addWidget(self.frametime, 0, 5, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 0, 1, 1)
        self.newMotionButton = QtWidgets.QPushButton(Hand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newMotionButton.sizePolicy().hasHeightForWidth())
        self.newMotionButton.setSizePolicy(sizePolicy)
        self.newMotionButton.setMaximumSize(QtCore.QSize(30, 30))
        self.newMotionButton.setObjectName("newMotionButton")
        self.gridLayout.addWidget(self.newMotionButton, 1, 1, 1, 1)
        self.addTimeButton = QtWidgets.QPushButton(Hand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addTimeButton.sizePolicy().hasHeightForWidth())
        self.addTimeButton.setSizePolicy(sizePolicy)
        self.addTimeButton.setMaximumSize(QtCore.QSize(30, 30))
        self.addTimeButton.setObjectName("addTimeButton")
        self.gridLayout.addWidget(self.addTimeButton, 1, 4, 1, 1)
        self.newMotionText = QtWidgets.QLineEdit(Hand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newMotionText.sizePolicy().hasHeightForWidth())
        self.newMotionText.setSizePolicy(sizePolicy)
        self.newMotionText.setObjectName("newMotionText")
        self.gridLayout.addWidget(self.newMotionText, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 3, 1, 1)
        self.motionList = QtWidgets.QComboBox(Hand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motionList.sizePolicy().hasHeightForWidth())
        self.motionList.setSizePolicy(sizePolicy)
        self.motionList.setObjectName("motionList")
        self.motionList.addItem("")
        self.motionList.addItem("")
        self.gridLayout.addWidget(self.motionList, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Hand)
        self.label_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 1, 5, 1, 2)
        self.addFrameButton = QtWidgets.QPushButton(Hand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addFrameButton.sizePolicy().hasHeightForWidth())
        self.addFrameButton.setSizePolicy(sizePolicy)
        self.addFrameButton.setObjectName("addFrameButton")
        self.gridLayout.addWidget(self.addFrameButton, 0, 6, 1, 1)
        self.label = QtWidgets.QLabel(Hand)
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.gridLayout_13.addLayout(self.gridLayout, 9, 2, 1, 2)
        self.pushButton = QtWidgets.QPushButton(Hand)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_13.addWidget(self.pushButton, 5, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(78, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem9, 7, 4, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(78, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem10, 5, 4, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(48, 88, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem11, 6, 2, 2, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.twoFinger = QtWidgets.QRadioButton(Hand)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.twoFinger.setFont(font)
        self.twoFinger.setObjectName("twoFinger")
        self.verticalLayout.addWidget(self.twoFinger)
        self.threeFinger = QtWidgets.QRadioButton(Hand)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.threeFinger.setFont(font)
        self.threeFinger.setObjectName("threeFinger")
        self.verticalLayout.addWidget(self.threeFinger)
        self.fourFinger = QtWidgets.QRadioButton(Hand)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fourFinger.setFont(font)
        self.fourFinger.setObjectName("fourFinger")
        self.verticalLayout.addWidget(self.fourFinger)
        self.fiveFinger = QtWidgets.QRadioButton(Hand)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fiveFinger.setFont(font)
        self.fiveFinger.setObjectName("fiveFinger")
        self.verticalLayout.addWidget(self.fiveFinger)
        self.serialButton = QtWidgets.QPushButton(Hand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serialButton.sizePolicy().hasHeightForWidth())
        self.serialButton.setSizePolicy(sizePolicy)
        self.serialButton.setCheckable(True)
        self.serialButton.setObjectName("serialButton")
        self.verticalLayout.addWidget(self.serialButton)
        self.gridLayout_13.addLayout(self.verticalLayout, 0, 3, 8, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem12, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Index = QtWidgets.QGroupBox(Hand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Index.sizePolicy().hasHeightForWidth())
        self.Index.setSizePolicy(sizePolicy)
        self.Index.setAlignment(QtCore.Qt.AlignCenter)
        self.Index.setObjectName("Index")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Index)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.DIPIndex = NormalJoint(self.Index)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DIPIndex.sizePolicy().hasHeightForWidth())
        self.DIPIndex.setSizePolicy(sizePolicy)
        self.DIPIndex.setObjectName("DIPIndex")
        self.gridLayout_2.addWidget(self.DIPIndex, 0, 0, 1, 2)
        self.PIPIndex = NormalJoint(self.Index)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PIPIndex.sizePolicy().hasHeightForWidth())
        self.PIPIndex.setSizePolicy(sizePolicy)
        self.PIPIndex.setObjectName("PIPIndex")
        self.gridLayout_2.addWidget(self.PIPIndex, 1, 0, 1, 2)
        self.MPIndex = NormalJoint(self.Index)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MPIndex.sizePolicy().hasHeightForWidth())
        self.MPIndex.setSizePolicy(sizePolicy)
        self.MPIndex.setObjectName("MPIndex")
        self.gridLayout_2.addWidget(self.MPIndex, 2, 0, 1, 2)
        self.ABIndex = NormalJoint(self.Index)
        self.ABIndex.setObjectName("ABIndex")
        self.gridLayout_2.addWidget(self.ABIndex, 3, 0, 1, 1)
        self.ADIndex = NormalJoint(self.Index)
        self.ADIndex.setObjectName("ADIndex")
        self.gridLayout_2.addWidget(self.ADIndex, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.Index)
        self.Middle = QtWidgets.QGroupBox(Hand)
        self.Middle.setAlignment(QtCore.Qt.AlignCenter)
        self.Middle.setObjectName("Middle")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Middle)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.DIPMiddle = NormalJoint(self.Middle)
        self.DIPMiddle.setObjectName("DIPMiddle")
        self.gridLayout_4.addWidget(self.DIPMiddle, 0, 0, 1, 2)
        self.PIPMiddle = NormalJoint(self.Middle)
        self.PIPMiddle.setObjectName("PIPMiddle")
        self.gridLayout_4.addWidget(self.PIPMiddle, 1, 0, 1, 2)
        self.MPMiddle = NormalJoint(self.Middle)
        self.MPMiddle.setObjectName("MPMiddle")
        self.gridLayout_4.addWidget(self.MPMiddle, 2, 0, 1, 2)
        self.ABMiddle = NormalJoint(self.Middle)
        self.ABMiddle.setObjectName("ABMiddle")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.ABMiddle)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_4.addWidget(self.ABMiddle, 3, 0, 1, 1)
        self.ADMiddle = NormalJoint(self.Middle)
        self.ADMiddle.setObjectName("ADMiddle")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.ADMiddle)
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_4.addWidget(self.ADMiddle, 3, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.Middle)
        self.Ring = QtWidgets.QGroupBox(Hand)
        self.Ring.setAlignment(QtCore.Qt.AlignCenter)
        self.Ring.setObjectName("Ring")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Ring)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.DIPRing = NormalJoint(self.Ring)
        self.DIPRing.setObjectName("DIPRing")
        self.gridLayout_6.addWidget(self.DIPRing, 0, 0, 1, 2)
        self.PIPRing = NormalJoint(self.Ring)
        self.PIPRing.setObjectName("PIPRing")
        self.gridLayout_6.addWidget(self.PIPRing, 1, 0, 1, 2)
        self.MPRing = NormalJoint(self.Ring)
        self.MPRing.setObjectName("MPRing")
        self.gridLayout_6.addWidget(self.MPRing, 2, 0, 1, 2)
        self.ABRing = NormalJoint(self.Ring)
        self.ABRing.setObjectName("ABRing")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.ABRing)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gridLayout_6.addWidget(self.ABRing, 3, 0, 1, 1)
        self.ADRing = NormalJoint(self.Ring)
        self.ADRing.setObjectName("ADRing")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.ADRing)
        self.horizontalLayout_7.setSpacing(1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_6.addWidget(self.ADRing, 3, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.Ring)
        self.Pinky = QtWidgets.QGroupBox(Hand)
        self.Pinky.setAlignment(QtCore.Qt.AlignCenter)
        self.Pinky.setObjectName("Pinky")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.Pinky)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.DIPPinky = NormalJoint(self.Pinky)
        self.DIPPinky.setObjectName("DIPPinky")
        self.gridLayout_8.addWidget(self.DIPPinky, 0, 0, 1, 2)
        self.PIPPinky = NormalJoint(self.Pinky)
        self.PIPPinky.setObjectName("PIPPinky")
        self.gridLayout_8.addWidget(self.PIPPinky, 1, 0, 1, 2)
        self.MPPinky = NormalJoint(self.Pinky)
        self.MPPinky.setObjectName("MPPinky")
        self.gridLayout_8.addWidget(self.MPPinky, 2, 0, 1, 2)
        self.ABPinky = NormalJoint(self.Pinky)
        self.ABPinky.setObjectName("ABPinky")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.ABPinky)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout_8.addWidget(self.ABPinky, 3, 0, 1, 1)
        self.ADPinky = NormalJoint(self.Pinky)
        self.ADPinky.setObjectName("ADPinky")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.ADPinky)
        self.horizontalLayout_9.setSpacing(1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout_8.addWidget(self.ADPinky, 3, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.Pinky)
        self.gridLayout_12.addLayout(self.horizontalLayout, 0, 1, 2, 3)
        self.Thumb = QtWidgets.QGroupBox(Hand)
        self.Thumb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Thumb.setObjectName("Thumb")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.Thumb)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.DPThumb = NormalJoint(self.Thumb)
        self.DPThumb.setObjectName("DPThumb")
        self.gridLayout_10.addWidget(self.DPThumb, 0, 0, 1, 2)
        self.MPThumb = NormalJoint(self.Thumb)
        self.MPThumb.setObjectName("MPThumb")
        self.gridLayout_10.addWidget(self.MPThumb, 1, 0, 1, 2)
        self.TPThumb = NormalJoint(self.Thumb)
        self.TPThumb.setObjectName("TPThumb")
        self.gridLayout_10.addWidget(self.TPThumb, 2, 0, 1, 2)
        self.PalmThumb = NormalJoint(self.Thumb)
        self.PalmThumb.setObjectName("PalmThumb")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.PalmThumb)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.gridLayout_10.addWidget(self.PalmThumb, 3, 0, 1, 1)
        self.PalmThumbBack = NormalJoint(self.Thumb)
        self.PalmThumbBack.setObjectName("PalmThumbBack")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.PalmThumbBack)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.gridLayout_10.addWidget(self.PalmThumbBack, 3, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.Thumb, 1, 0, 2, 1)
        spacerItem13 = QtWidgets.QSpacerItem(178, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem13, 2, 1, 1, 1)
        self.PalmPinky = NormalJoint(Hand)
        self.PalmPinky.setObjectName("PalmPinky")
        self.gridLayout_12.addWidget(self.PalmPinky, 2, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(236, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem14, 2, 3, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 0, 1, 9, 1)
        self.plotDialogButton = QtWidgets.QPushButton(Hand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotDialogButton.sizePolicy().hasHeightForWidth())
        self.plotDialogButton.setSizePolicy(sizePolicy)
        self.plotDialogButton.setObjectName("plotDialogButton")
        self.gridLayout_13.addWidget(self.plotDialogButton, 3, 0, 1, 1)
        self.savePlotButton = QtWidgets.QPushButton(Hand)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savePlotButton.sizePolicy().hasHeightForWidth())
        self.savePlotButton.setSizePolicy(sizePolicy)
        self.savePlotButton.setObjectName("savePlotButton")
        self.gridLayout_13.addWidget(self.savePlotButton, 4, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_13, 0, 0, 1, 1)

        self.retranslateUi(Hand)
        self.DIPIndex.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.PIPIndex.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.MPIndex.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.ABIndex.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.ADIndex.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.DIPMiddle.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.PIPMiddle.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.MPMiddle.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.ABMiddle.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.ADMiddle.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.DIPRing.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.PIPRing.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.MPRing.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.ABRing.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.ADRing.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.DIPPinky.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.PIPPinky.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.MPPinky.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.ABPinky.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.ADPinky.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.PalmPinky.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.DPThumb.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.MPThumb.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.TPThumb.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.PalmThumb.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.addFrameButton.clicked.connect(Hand.slotSendFrame)
        self.leapMotionButton.toggled['bool'].connect(Hand.slotLeapMotionClicked)
        self.newMotionButton.clicked.connect(Hand.slotNewMotionClicked)
        self.addTimeButton.clicked.connect(Hand.slotAddTimeClicked)
        self.PalmThumbBack.sigValueChanged['int','float','int'].connect(Hand.slotValueChanged)
        self.plotDialogButton.clicked.connect(Hand.slotPlotDialogButtonClicked)
        self.savePlotButton.clicked.connect(Hand.slotSavePlotData)
        self.joyStickButton.toggled['bool'].connect(Hand.slotJoyStickClicked)
        self.pushButton.clicked.connect(Hand.slotMapToFingers)
        QtCore.QMetaObject.connectSlotsByName(Hand)

    def retranslateUi(self, Hand):
        _translate = QtCore.QCoreApplication.translate
        Hand.setWindowTitle(_translate("Hand", "Form"))
        self.joyStickButton.setText(_translate("Hand", "JoyStick"))
        self.leapMotionButton.setText(_translate("Hand", "Leap Motion"))
        self.newMotionButton.setText(_translate("Hand", "+"))
        self.addTimeButton.setText(_translate("Hand", "+1"))
        self.motionList.setItemText(0, _translate("Hand", "grasp"))
        self.motionList.setItemText(1, _translate("Hand", "wave"))
        self.label_2.setText(_translate("Hand", "at T ="))
        self.addFrameButton.setText(_translate("Hand", "Add"))
        self.label.setText(_translate("Hand", "Motion:"))
        self.pushButton.setText(_translate("Hand", "Map to"))
        self.twoFinger.setText(_translate("Hand", "Two Fingers"))
        self.threeFinger.setText(_translate("Hand", "Three Fingers"))
        self.fourFinger.setText(_translate("Hand", "Four Fingers"))
        self.fiveFinger.setText(_translate("Hand", "Five Fingers"))
        self.serialButton.setText(_translate("Hand", "Sync Soft Hand"))
        self.Index.setTitle(_translate("Hand", "Index"))
        self.Middle.setTitle(_translate("Hand", "Middle"))
        self.Ring.setTitle(_translate("Hand", "Ring"))
        self.Pinky.setTitle(_translate("Hand", "Pinky"))
        self.Thumb.setTitle(_translate("Hand", "Thumb"))
        self.plotDialogButton.setText(_translate("Hand", "Plots"))
        self.savePlotButton.setText(_translate("Hand", "SavePlot"))

from NormalJoint import NormalJoint
