# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\40207\OneDrive\OneDriveDocumentation\PythonWorkSpace\serialRT\serialRT\UIHandDialogPlot.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_handPlotDialog(object):
    def setupUi(self, handPlotDialog):
        handPlotDialog.setObjectName("handPlotDialog")
        handPlotDialog.resize(739, 432)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(handPlotDialog.sizePolicy().hasHeightForWidth())
        handPlotDialog.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(handPlotDialog)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16000))
        self.tabWidget.setObjectName("tabWidget")
        self.tabSingle = QtWidgets.QWidget()
        self.tabSingle.setObjectName("tabSingle")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabSingle)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.view26 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view26.sizePolicy().hasHeightForWidth())
        self.view26.setSizePolicy(sizePolicy)
        self.view26.setMinimumSize(QtCore.QSize(0, 0))
        self.view26.setObjectName("view26")
        self.gridLayout.addWidget(self.view26, 0, 0, 1, 5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.savePlotButton = QtWidgets.QPushButton(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savePlotButton.sizePolicy().hasHeightForWidth())
        self.savePlotButton.setSizePolicy(sizePolicy)
        self.savePlotButton.setObjectName("savePlotButton")
        self.verticalLayout.addWidget(self.savePlotButton)
        self.clearPlotButton = QtWidgets.QPushButton(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearPlotButton.sizePolicy().hasHeightForWidth())
        self.clearPlotButton.setSizePolicy(sizePolicy)
        self.clearPlotButton.setObjectName("clearPlotButton")
        self.verticalLayout.addWidget(self.clearPlotButton)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.view15 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view15.sizePolicy().hasHeightForWidth())
        self.view15.setSizePolicy(sizePolicy)
        self.view15.setObjectName("view15")
        self.gridLayout.addWidget(self.view15, 1, 1, 1, 1)
        self.view10 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view10.sizePolicy().hasHeightForWidth())
        self.view10.setSizePolicy(sizePolicy)
        self.view10.setObjectName("view10")
        self.gridLayout.addWidget(self.view10, 1, 2, 1, 1)
        self.view5 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view5.sizePolicy().hasHeightForWidth())
        self.view5.setSizePolicy(sizePolicy)
        self.view5.setObjectName("view5")
        self.gridLayout.addWidget(self.view5, 1, 3, 1, 1)
        self.view0 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view0.sizePolicy().hasHeightForWidth())
        self.view0.setSizePolicy(sizePolicy)
        self.view0.setObjectName("view0")
        self.gridLayout.addWidget(self.view0, 1, 4, 1, 1)
        self.view16 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view16.sizePolicy().hasHeightForWidth())
        self.view16.setSizePolicy(sizePolicy)
        self.view16.setObjectName("view16")
        self.gridLayout.addWidget(self.view16, 2, 1, 1, 1)
        self.view11 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view11.sizePolicy().hasHeightForWidth())
        self.view11.setSizePolicy(sizePolicy)
        self.view11.setObjectName("view11")
        self.gridLayout.addWidget(self.view11, 2, 2, 1, 1)
        self.view6 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view6.sizePolicy().hasHeightForWidth())
        self.view6.setSizePolicy(sizePolicy)
        self.view6.setObjectName("view6")
        self.gridLayout.addWidget(self.view6, 2, 3, 1, 1)
        self.view1 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view1.sizePolicy().hasHeightForWidth())
        self.view1.setSizePolicy(sizePolicy)
        self.view1.setObjectName("view1")
        self.gridLayout.addWidget(self.view1, 2, 4, 1, 1)
        self.view20 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view20.sizePolicy().hasHeightForWidth())
        self.view20.setSizePolicy(sizePolicy)
        self.view20.setObjectName("view20")
        self.gridLayout.addWidget(self.view20, 3, 0, 1, 1)
        self.view17 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view17.sizePolicy().hasHeightForWidth())
        self.view17.setSizePolicy(sizePolicy)
        self.view17.setObjectName("view17")
        self.gridLayout.addWidget(self.view17, 3, 1, 1, 1)
        self.view12 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view12.sizePolicy().hasHeightForWidth())
        self.view12.setSizePolicy(sizePolicy)
        self.view12.setObjectName("view12")
        self.gridLayout.addWidget(self.view12, 3, 2, 1, 1)
        self.view7 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view7.sizePolicy().hasHeightForWidth())
        self.view7.setSizePolicy(sizePolicy)
        self.view7.setObjectName("view7")
        self.gridLayout.addWidget(self.view7, 3, 3, 1, 1)
        self.view2 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view2.sizePolicy().hasHeightForWidth())
        self.view2.setSizePolicy(sizePolicy)
        self.view2.setObjectName("view2")
        self.gridLayout.addWidget(self.view2, 3, 4, 1, 1)
        self.view21 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view21.sizePolicy().hasHeightForWidth())
        self.view21.setSizePolicy(sizePolicy)
        self.view21.setObjectName("view21")
        self.gridLayout.addWidget(self.view21, 4, 0, 1, 1)
        self.view18 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view18.sizePolicy().hasHeightForWidth())
        self.view18.setSizePolicy(sizePolicy)
        self.view18.setObjectName("view18")
        self.gridLayout.addWidget(self.view18, 4, 1, 1, 1)
        self.view13 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view13.sizePolicy().hasHeightForWidth())
        self.view13.setSizePolicy(sizePolicy)
        self.view13.setObjectName("view13")
        self.gridLayout.addWidget(self.view13, 4, 2, 1, 1)
        self.view8 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view8.sizePolicy().hasHeightForWidth())
        self.view8.setSizePolicy(sizePolicy)
        self.view8.setObjectName("view8")
        self.gridLayout.addWidget(self.view8, 4, 3, 1, 1)
        self.view3 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view3.sizePolicy().hasHeightForWidth())
        self.view3.setSizePolicy(sizePolicy)
        self.view3.setObjectName("view3")
        self.gridLayout.addWidget(self.view3, 4, 4, 1, 1)
        self.view22 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view22.sizePolicy().hasHeightForWidth())
        self.view22.setSizePolicy(sizePolicy)
        self.view22.setObjectName("view22")
        self.gridLayout.addWidget(self.view22, 5, 0, 1, 1)
        self.view19 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view19.sizePolicy().hasHeightForWidth())
        self.view19.setSizePolicy(sizePolicy)
        self.view19.setObjectName("view19")
        self.gridLayout.addWidget(self.view19, 5, 1, 1, 1)
        self.view14 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view14.sizePolicy().hasHeightForWidth())
        self.view14.setSizePolicy(sizePolicy)
        self.view14.setObjectName("view14")
        self.gridLayout.addWidget(self.view14, 5, 2, 1, 1)
        self.view9 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view9.sizePolicy().hasHeightForWidth())
        self.view9.setSizePolicy(sizePolicy)
        self.view9.setObjectName("view9")
        self.gridLayout.addWidget(self.view9, 5, 3, 1, 1)
        self.view4 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view4.sizePolicy().hasHeightForWidth())
        self.view4.setSizePolicy(sizePolicy)
        self.view4.setObjectName("view4")
        self.gridLayout.addWidget(self.view4, 5, 4, 1, 1)
        self.view23 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view23.sizePolicy().hasHeightForWidth())
        self.view23.setSizePolicy(sizePolicy)
        self.view23.setObjectName("view23")
        self.gridLayout.addWidget(self.view23, 6, 0, 1, 1)
        self.view24 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view24.sizePolicy().hasHeightForWidth())
        self.view24.setSizePolicy(sizePolicy)
        self.view24.setObjectName("view24")
        self.gridLayout.addWidget(self.view24, 6, 1, 1, 1)
        self.view25 = PlotWidget(self.tabSingle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view25.sizePolicy().hasHeightForWidth())
        self.view25.setSizePolicy(sizePolicy)
        self.view25.setObjectName("view25")
        self.gridLayout.addWidget(self.view25, 6, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabSingle, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.view3D = GLViewWidget(self.tab_6)
        self.view3D.setObjectName("view3D")
        self.gridLayout_3.addWidget(self.view3D, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.gridLayout_5.addWidget(self.tabWidget, 0, 0, 1, 1)
        handPlotDialog.setCentralWidget(self.centralwidget)
        self.actionsaveData = QtWidgets.QAction(handPlotDialog)
        self.actionsaveData.setObjectName("actionsaveData")
        self.actionclearData = QtWidgets.QAction(handPlotDialog)
        self.actionclearData.setObjectName("actionclearData")

        self.retranslateUi(handPlotDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(handPlotDialog)

    def retranslateUi(self, handPlotDialog):
        _translate = QtCore.QCoreApplication.translate
        handPlotDialog.setWindowTitle(_translate("handPlotDialog", "Pressure Plot"))
        self.savePlotButton.setText(_translate("handPlotDialog", "Save"))
        self.clearPlotButton.setText(_translate("handPlotDialog", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSingle), _translate("handPlotDialog", "Individual"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("handPlotDialog", "3D"))
        self.actionsaveData.setText(_translate("handPlotDialog", "saveData"))
        self.actionclearData.setText(_translate("handPlotDialog", "clearData"))

from pyqtgraph import PlotWidget
from pyqtgraph.opengl import GLViewWidget
