# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\40207\OneDrive\OneDriveDocumentation\PythonWorkSpace\serialRT\serialRT\UINormalJointDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_normalJointDialog(object):
    def setupUi(self, normalJointDialog):
        normalJointDialog.setObjectName("normalJointDialog")
        normalJointDialog.resize(616, 534)
        self.gridLayout = QtWidgets.QGridLayout(normalJointDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openingMinN = SpinBox(normalJointDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openingMinN.sizePolicy().hasHeightForWidth())
        self.openingMinN.setSizePolicy(sizePolicy)
        self.openingMinN.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setItalic(True)
        self.openingMinN.setFont(font)
        self.openingMinN.setAlignment(QtCore.Qt.AlignCenter)
        self.openingMinN.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.openingMinN.setObjectName("openingMinN")
        self.horizontalLayout.addWidget(self.openingMinN)
        self.openingMaxN = SpinBox(normalJointDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openingMaxN.sizePolicy().hasHeightForWidth())
        self.openingMaxN.setSizePolicy(sizePolicy)
        self.openingMaxN.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setItalic(True)
        self.openingMaxN.setFont(font)
        self.openingMaxN.setAlignment(QtCore.Qt.AlignCenter)
        self.openingMaxN.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.openingMaxN.setObjectName("openingMaxN")
        self.horizontalLayout.addWidget(self.openingMaxN)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.openingMinP = SpinBox(normalJointDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openingMinP.sizePolicy().hasHeightForWidth())
        self.openingMinP.setSizePolicy(sizePolicy)
        self.openingMinP.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setItalic(True)
        self.openingMinP.setFont(font)
        self.openingMinP.setAlignment(QtCore.Qt.AlignCenter)
        self.openingMinP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.openingMinP.setObjectName("openingMinP")
        self.horizontalLayout.addWidget(self.openingMinP)
        self.openingMaxP = SpinBox(normalJointDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openingMaxP.sizePolicy().hasHeightForWidth())
        self.openingMaxP.setSizePolicy(sizePolicy)
        self.openingMaxP.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setItalic(True)
        self.openingMaxP.setFont(font)
        self.openingMaxP.setAlignment(QtCore.Qt.AlignCenter)
        self.openingMaxP.setReadOnly(False)
        self.openingMaxP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.openingMaxP.setObjectName("openingMaxP")
        self.horizontalLayout.addWidget(self.openingMaxP)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table = QtWidgets.QTableView(normalJointDialog)
        self.table.setObjectName("table")
        self.verticalLayout.addWidget(self.table)
        self.relationPlotWidget = PlotWidget(normalJointDialog)
        self.relationPlotWidget.setObjectName("relationPlotWidget")
        self.verticalLayout.addWidget(self.relationPlotWidget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(normalJointDialog)
        QtCore.QMetaObject.connectSlotsByName(normalJointDialog)

    def retranslateUi(self, normalJointDialog):
        _translate = QtCore.QCoreApplication.translate
        normalJointDialog.setWindowTitle(_translate("normalJointDialog", "Dialog"))
        self.openingMinN.setToolTip(_translate("normalJointDialog", "openingMinN"))
        self.openingMaxN.setToolTip(_translate("normalJointDialog", "openingMaxN"))
        self.openingMinP.setToolTip(_translate("normalJointDialog", "openingMinP"))
        self.openingMaxP.setToolTip(_translate("normalJointDialog", "openingMaxP"))

from pyqtgraph import PlotWidget, SpinBox
