# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\40207\OneDrive\OneDriveDocumentation\PythonWorkSpace\serialRT\serialRT\UINormalJoint.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_normalJoint(object):
    def setupUi(self, normalJoint):
        normalJoint.setObjectName("normalJoint")
        normalJoint.resize(142, 107)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(normalJoint.sizePolicy().hasHeightForWidth())
        normalJoint.setSizePolicy(sizePolicy)
        normalJoint.setMaximumSize(QtCore.QSize(116775, 116775))
        self.gridLayout_2 = QtWidgets.QGridLayout(normalJoint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.digit = QtWidgets.QGroupBox(normalJoint)
        self.digit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.digit.setFlat(False)
        self.digit.setCheckable(False)
        self.digit.setObjectName("digit")
        self.gridLayout = QtWidgets.QGridLayout(self.digit)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pressure = QtWidgets.QSpinBox(self.digit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pressure.sizePolicy().hasHeightForWidth())
        self.pressure.setSizePolicy(sizePolicy)
        self.pressure.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pressure.setFont(font)
        self.pressure.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pressure.setAutoFillBackground(False)
        self.pressure.setAlignment(QtCore.Qt.AlignCenter)
        self.pressure.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pressure.setMaximum(200)
        self.pressure.setObjectName("pressure")
        self.gridLayout.addWidget(self.pressure, 0, 1, 1, 1)
        self.chamberNum = QtWidgets.QPushButton(self.digit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chamberNum.sizePolicy().hasHeightForWidth())
        self.chamberNum.setSizePolicy(sizePolicy)
        self.chamberNum.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.chamberNum.setFont(font)
        self.chamberNum.setCheckable(False)
        self.chamberNum.setObjectName("chamberNum")
        self.gridLayout.addWidget(self.chamberNum, 0, 0, 1, 1)
        self.angle = QtWidgets.QSpinBox(self.digit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.angle.sizePolicy().hasHeightForWidth())
        self.angle.setSizePolicy(sizePolicy)
        self.angle.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.angle.setFont(font)
        self.angle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.angle.setAutoFillBackground(False)
        self.angle.setAlignment(QtCore.Qt.AlignCenter)
        self.angle.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.angle.setMaximum(120)
        self.angle.setObjectName("angle")
        self.gridLayout.addWidget(self.angle, 1, 1, 1, 1)
        self.angleReal = QtWidgets.QLabel(self.digit)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.angleReal.setFont(font)
        self.angleReal.setAlignment(QtCore.Qt.AlignCenter)
        self.angleReal.setObjectName("angleReal")
        self.gridLayout.addWidget(self.angleReal, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.digit, 0, 0, 1, 1)

        self.retranslateUi(normalJoint)
        self.angle.valueChanged['int'].connect(normalJoint.slotAngleValueChanged)
        self.pressure.valueChanged['int'].connect(normalJoint.slotPressureValueChanged)
        self.chamberNum.clicked['bool'].connect(normalJoint.slotPressureHoldClicked)
        QtCore.QMetaObject.connectSlotsByName(normalJoint)

    def retranslateUi(self, normalJoint):
        _translate = QtCore.QCoreApplication.translate
        normalJoint.setWindowTitle(_translate("normalJoint", "Form"))
        self.digit.setTitle(_translate("normalJoint", "DIP"))
        self.chamberNum.setText(_translate("normalJoint", "p"))
        self.angleReal.setText(_translate("normalJoint", "0"))

